version: '3.9'
services:
  countries-mvc:
    image: erikrasniqi/countries-mvc:0.0.1.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - countries-db
    networks:
      - country-network

  # The value of 'DB_HOST' we reference in the MVC Dockerfile  
  countries-db:
    image: erikrasniqi/countries-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - country-network
      
networks:
  country-network: