- hosts: dev
  become: true
  tasks:
    - name: Install Docker on Amazon Linux 2
      shell: "amazon-linux-extras install docker -y"
      ignore_errors: true

    - name: Install Docker on Amazon Linux 2023 or others
      yum:
        name: docker
        state: present
      when: ansible_distribution_major_version is version('2', '>')

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user # Update this path to where your docker-compose.yml is located
